### ISSUE TITLE
Need a BAM-to-FastQ workflow

### ISSUE THREAD

**Issue by kevinlibuit** [theiagen/terra_utilities#1]

**Comment by kapsakcj** [comment]
[copying my messages from slack on this]

Regarding the labs submitting BAMs, I'm thinking it would probably be best to use `bedtools bamtofastq` as a way to extract reads if we need to verify the PANGO lineage or NextClade designation

https://bedtools.readthedocs.io/en/latest/content/tools/bamtofastq.html

open to other tools too, I just trust bedtools to do what we want without issues. Plus we have a docker image ready to go in staphb/docker-builds 

It may be a little bit tricky though, because we'll have to know beforehand if the BAMs have single-end or paired-end reads in them

**Comment by kevinlibuit** [comment]
Made available in the v1.2.0 release through the BAM to FASTQ (SE/PE) workflows
- Written with the `samtools fastq` module
